import sys

out = []
out.append('    <RegisterGroup description="Generic Interrupt Controller CPU Interface (GICC)" name="GICC" start="0x50802000">')
out.append('        <Register access="Read/Write" description="CPU Interface Control Register" name="GICC_CTLR" reset_mask="0xFFFFFFFF" reset_value="0x00000000" size="4" start="+0x0">')
out.append('            <BitField description="Enable Group 0" name="EnableGrp0" size="1" start="0" />')
out.append('            <BitField description="Enable Group 1" name="EnableGrp1" size="1" start="1" />')
out.append('            <BitField description="AckCtl" name="AckCtl" size="1" start="2" />')
out.append('            <BitField description="FIQEn" name="FIQEn" size="1" start="3" />')
out.append('            <BitField description="CBPR" name="CBPR" size="1" start="4" />')
out.append('            <BitField description="FIQ bypass disable" name="FIQBypDisGrp0" size="1" start="5" />')
out.append('            <BitField description="IRQ bypass disable" name="IRQBypDisGrp0" size="1" start="6" />')
out.append('        </Register>')
out.append('        <Register access="Read/Write" description="Interrupt Priority Mask Register" name="GICC_PMR" reset_mask="0xFFFFFFFF" reset_value="0x00000000" size="4" start="+0x4" />')
out.append('        <Register access="Read/Write" description="Binary Point Register" name="GICC_BPR" reset_mask="0xFFFFFFFF" reset_value="0x00000002" size="4" start="+0x8" />')
out.append('        <Register access="ReadOnly" description="Interrupt Acknowledge Register" name="GICC_IAR" reset_mask="0xFFFFFFFF" reset_value="0x00000000" size="4" start="+0xC">')
out.append('            <BitField description="Interrupt ID" name="InterruptID" size="10" start="0" />')
out.append('            <BitField description="CPUID" name="CPUID" size="3" start="10" />')
out.append('        </Register>')
out.append('        <Register access="WriteOnly" description="End of Interrupt Register" name="GICC_EOIR" reset_mask="0xFFFFFFFF" reset_value="0x00000000" size="4" start="+0x10">')
out.append('            <BitField description="Interrupt ID" name="InterruptID" size="10" start="0" />')
out.append('            <BitField description="CPUID" name="CPUID" size="3" start="10" />')
out.append('        </Register>')
out.append('        <Register access="ReadOnly" description="Running Priority Register" name="GICC_RPR" reset_mask="0xFFFFFFFF" reset_value="0x000000FF" size="4" start="+0x14" />')
out.append('        <Register access="ReadOnly" description="Highest Priority Pending Interrupt Register" name="GICC_HPPIR" reset_mask="0xFFFFFFFF" reset_value="0x000003FF" size="4" start="+0x18" />')
out.append('        <Register access="Read/Write" description="Aliased Binary Point Register" name="GICC_ABPR" reset_mask="0xFFFFFFFF" reset_value="0x00000003" size="4" start="+0x1C" />')
out.append('        <Register access="ReadOnly" description="Aliased Interrupt Acknowledge Register" name="GICC_AIAR" reset_mask="0xFFFFFFFF" reset_value="0x000003FF" size="4" start="+0x20" />')
out.append('        <Register access="WriteOnly" description="Aliased End of Interrupt Register" name="GICC_AEOIR" reset_mask="0xFFFFFFFF" reset_value="0x00000000" size="4" start="+0x24" />')
out.append('        <Register access="ReadOnly" description="Aliased Highest Priority Pending Interrupt Register" name="GICC_AHPPIR" reset_mask="0xFFFFFFFF" reset_value="0x000003FF" size="4" start="+0x28" />')
out.append('        <Register access="ReadOnly" description="CPU Interface Identification Register" name="GICC_IIDR" reset_mask="0xFFFFFFFF" reset_value="0x00000000" size="4" start="+0xFC" />')
out.append('        <Register access="WriteOnly" description="Deactivate Interrupt Register" name="GICC_DIR" reset_mask="0xFFFFFFFF" reset_value="0x00000000" size="4" start="+0x1000" />')
out.append('    </RegisterGroup>')

with open("gicc_block.xml", "w") as f:
    f.write("\n".join(out) + "\n")
